config/routes.rb
Rails.application.routes.draw do

  resources :orders
  resources :editions
  resources :subscriptions
  resources :publications
  get '/home/welcome', to: 'home#welcome'

  resources :uploads
  resources :deductions
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :customers
  resources :equipment
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

 # You can have the root of your site routed with "root"
  root to: 'home#index'
  get '/Sender', to: 'chat#Sender'
  get '/ReceiverOne', to: 'chat#ReceiverOne'
  get '/ReceiverTwo', to: 'chat#ReceiverTwo'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :orders
end

app/models/deduction.rb
class Deduction < ApplicationRecord
	belongs_to :equipment
end

app/models/edition.rb
class Edition < ApplicationRecord
  belongs_to :publication
end

app/models/equipment.rb
class Equipment < ApplicationRecord
	has_one :deduction
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  belongs_to :publication
  belongs_to :edition

  def self.search(search)
    if search
        where(["edition_id LIKE ?","%#{search}%"])
      else
        all
      end
    end
end

app/models/publication.rb
class Publication < ApplicationRecord
  has_many :subscriptions
  has_many :customers, :through => :subscriptions
  has_many :editions
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :customer
  belongs_to :publication

  def self.search(search)
    if search
        where(["publication_id LIKE ?","%#{search}%"])
      else
        all
      end
    end
end

app/models/upload.rb
class Upload < ApplicationRecord
belongs_to :user	
has_attached_file :image,
                storage: :s3,
              	s3_credentials: {access_key_id: ENV["AWS_KEY"], 
              	secret_access_key: ENV["AWS_SECRET"]},
              	bucket: "yghdassets"

validates_attachment_content_type :image, content_type: [/\Avideo\/.*\Z/, /\Aimage\/.*\Z/, /\Aapplication\/.*\Z/]
validates :submitter, presence: true
validates :email, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :registerable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/editions_controller.rb
class EditionsController < ApplicationController
  before_action :set_edition, only: [:show, :edit, :update, :destroy]

  # GET /editions
  # GET /editions.json
  def index
    @editions = Edition.all
    @publications = Publication.all
  end

  # GET /editions/1
  # GET /editions/1.json
  def show
  end

  # GET /editions/new
  def new
    @edition = Edition.new
  end

  # GET /editions/1/edit
  def edit
  end

  # POST /editions
  # POST /editions.json
  def create
    @edition = Edition.new(edition_params)

    respond_to do |format|
      if @edition.save
        format.html { redirect_to @edition, notice: 'Edition was successfully created.' }
        format.json { render :show, status: :created, location: @edition }
      else
        format.html { render :new }
        format.json { render json: @edition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /editions/1
  # PATCH/PUT /editions/1.json
  def update
    respond_to do |format|
      if @edition.update(edition_params)
        format.html { redirect_to @edition, notice: 'Edition was successfully updated.' }
        format.json { render :show, status: :ok, location: @edition }
      else
        format.html { render :edit }
        format.json { render json: @edition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /editions/1
  # DELETE /editions/1.json
  def destroy
    @edition.destroy
    respond_to do |format|
      format.html { redirect_to editions_url, notice: 'Edition was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_edition
      @edition = Edition.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def edition_params
      params.require(:edition).permit(:publication_id, :month, :year, :number, :volume, :description)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_helper.rb
module ChatHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/deductions_helper.rb
module DeductionsHelper
end

app/helpers/editions_helper.rb
module EditionsHelper
end

app/helpers/equipment_helper.rb
module EquipmentHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/editions/_form.html.erb
<%= form_for(edition) do |f| %>
  <% if edition.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(edition.errors.count, "error") %> prohibited this edition from being saved:</h2>

      <ul>
      <% edition.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.collection_select( :publication_id, Publication.all, :id, :name) %>
  </div>

  <div class="field">
    <%= f.label :month %>
    <%= f.text_field :month %>
  </div>

  <div class="field">
    <%= f.label :year %>
    <%= f.text_field :year %>
  </div>

  <div class="field">
    <%= f.label :number %>
    <%= f.number_field :number %>
  </div>

  <div class="field">
    <%= f.label :volume %>
    <%= f.number_field :volume %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/editions/edit.html.erb
<h1>Editing Edition</h1>

<%= render 'form', edition: @edition %>

<%= link_to 'Show', @edition %> |
<%= link_to 'Back', editions_path %>

app/views/editions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Editions</h1>

<table>
  <thead>
    <tr>
      <th>Edition Name</th>
      <th>Publication</th>
      <th>Month</th>
      <th>Year</th>
      <th>Number</th>
      <th>Volume</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @editions.each do |edition| %>
      <tr>
        <td><%= edition.name %></td>
        <td><%= edition.publication.name %></td>
        <td><%= edition.month %></td>
        <td><%= edition.year %></td>
        <td><%= edition.number %></td>
        <td><%= edition.volume %></td>
        <td><%= edition.description %></td>
        <td><%= link_to 'Show', edition %></td>
        <td><%= link_to 'Edit', edit_edition_path(edition) %></td>
        <td><%= link_to 'Destroy', edition, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to 'Home', '/' %>  |
<%= link_to 'New Edition', new_edition_path %>

app/views/editions/new.html.erb
<h1>New Edition</h1>

<%= render 'form', edition: @edition %>

<%= link_to 'Back', editions_path %>

app/views/editions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Publication:</strong>
  <%= @edition.publication_id %>
</p>

<p>
  <strong>Month:</strong>
  <%= @edition.month %>
</p>

<p>
  <strong>Year:</strong>
  <%= @edition.year %>
</p>

<p>
  <strong>Number:</strong>
  <%= @edition.number %>
</p>

<p>
  <strong>Volume:</strong>
  <%= @edition.volume %>
</p>

<p>
  <strong>Description:</strong>
  <%= @edition.description %>
</p>

<%= link_to 'Edit', edit_edition_path(@edition) %> |
<%= link_to 'Back', editions_path %>