config/routes.rb
Rails.application.routes.draw do

  resources :orders
  resources :editions
  resources :subscriptions
  resources :publications
  get '/home/welcome', to: 'home#welcome'

  resources :uploads
  resources :deductions
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :customers
  resources :equipment
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

 # You can have the root of your site routed with "root"
  root to: 'home#index'
  get '/Sender', to: 'chat#Sender'
  get '/ReceiverOne', to: 'chat#ReceiverOne'
  get '/ReceiverTwo', to: 'chat#ReceiverTwo'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :orders
end

app/models/deduction.rb
class Deduction < ApplicationRecord
	belongs_to :equipment
end

app/models/edition.rb
class Edition < ApplicationRecord
  belongs_to :publication
end

app/models/equipment.rb
class Equipment < ApplicationRecord
	has_one :deduction
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  belongs_to :publication
  belongs_to :edition

  def self.search(search)
    if search
        where(["edition_id LIKE ?","%#{search}%"])
      else
        all
      end
    end
end

app/models/publication.rb
class Publication < ApplicationRecord
  has_many :subscriptions
  has_many :customers, :through => :subscriptions
  has_many :editions
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :customer
  belongs_to :publication

  def self.search(search)
    if search
        where(["publication_id LIKE ?","%#{search}%"])
      else
        all
      end
    end
end

app/models/upload.rb
class Upload < ApplicationRecord
belongs_to :user	
has_attached_file :image,
                storage: :s3,
              	s3_credentials: {access_key_id: ENV["AWS_KEY"], 
              	secret_access_key: ENV["AWS_SECRET"]},
              	bucket: "yghdassets"

validates_attachment_content_type :image, content_type: [/\Avideo\/.*\Z/, /\Aimage\/.*\Z/, /\Aapplication\/.*\Z/]
validates :submitter, presence: true
validates :email, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :registerable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  before_action :set_publication, only: [:show, :edit, :update, :destroy]

  # GET /publications
  # GET /publications.json
  def index
    @publications = Publication.all
  end

  # GET /publications/1
  # GET /publications/1.json
  def show
  end

  # GET /publications/new
  def new
    @publication = Publication.new
  end

  # GET /publications/1/edit
  def edit
  end

  # POST /publications
  # POST /publications.json
  def create
    @publication = Publication.new(publication_params)

    respond_to do |format|
      if @publication.save
        format.html { redirect_to @publication, notice: 'Publication was successfully created.' }
        format.json { render :show, status: :created, location: @publication }
      else
        format.html { render :new }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publications/1
  # PATCH/PUT /publications/1.json
  def update
    respond_to do |format|
      if @publication.update(publication_params)
        format.html { redirect_to @publication, notice: 'Publication was successfully updated.' }
        format.json { render :show, status: :ok, location: @publication }
      else
        format.html { render :edit }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publications/1
  # DELETE /publications/1.json
  def destroy
    @publication.destroy
    respond_to do |format|
      format.html { redirect_to publications_url, notice: 'Publication was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_publication
      @publication = Publication.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def publication_params
      params.require(:publication).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_helper.rb
module ChatHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/deductions_helper.rb
module DeductionsHelper
end

app/helpers/editions_helper.rb
module EditionsHelper
end

app/helpers/equipment_helper.rb
module EquipmentHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/publications/_form.html.erb
<%= form_for(publication) do |f| %>
  <% if publication.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(publication.errors.count, "error") %> prohibited this publication from being saved:</h2>

      <ul>
      <% publication.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/publications/edit.html.erb
<h1>Editing Publication</h1>

<%= render 'form', publication: @publication %>

<%= link_to 'Show', @publication %> |
<%= link_to 'Back', publications_path %>

app/views/publications/index.html.erb
<p id="notice"><%= notice %></p>

<br>
<div class="jumbotron">
  <h1>Publications</h1>
  <p>Welcome to the publications area.</p>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Actions</h3>
  </div>
  <div class="panel-body">

<a class="btn btn-primary btn-lg btn-block" href="/publications/new" role="button">New Publication</a>

</div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Publications</h3>
  </div>
  <div class="panel-body">
      <div class="table-responsive">
      <table class="table table-striped">

        <thead>
          <tr>
            <th>Name</th>
            <th>Description</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @publications.each do |publication| %>
            <tr>
              <td><%= publication.name %></td>
              <td><%= publication.description %></td>
              <td><%= link_to 'Show', publication %></td>
              <td><%= link_to 'Edit', edit_publication_path(publication) %></td>
              <td><%= link_to 'Destroy', publication, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
</div>
</div>
</div>


<br>

<br>

<%= link_to 'Home', '/' %>  |
<%= link_to 'New Publication', new_publication_path %>

app/views/publications/new.html.erb
<h1>New Publication</h1>

<%= render 'form', publication: @publication %>

<%= link_to 'Back', publications_path %>

app/views/publications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>String:</strong>
  <%= @publication.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @publication.description %>
</p>

<%= link_to 'Edit', edit_publication_path(@publication) %> |
<%= link_to 'Back', publications_path %>