config/routes.rb
Rails.application.routes.draw do

  resources :orders
  resources :editions
  resources :subscriptions
  resources :publications
  get '/home/welcome', to: 'home#welcome'

  resources :uploads
  resources :deductions
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :customers
  resources :equipment
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

 # You can have the root of your site routed with "root"
  root to: 'home#index'
  get '/Sender', to: 'chat#Sender'
  get '/ReceiverOne', to: 'chat#ReceiverOne'
  get '/ReceiverTwo', to: 'chat#ReceiverTwo'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :orders
end

app/models/deduction.rb
class Deduction < ApplicationRecord
	belongs_to :equipment
end

app/models/edition.rb
class Edition < ApplicationRecord
  belongs_to :publication
end

app/models/equipment.rb
class Equipment < ApplicationRecord
	has_one :deduction
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  belongs_to :publication
  belongs_to :edition

  def self.search(search)
    if search
        where(["edition_id LIKE ?","%#{search}%"])
      else
        all
      end
    end
end

app/models/publication.rb
class Publication < ApplicationRecord
  has_many :subscriptions
  has_many :customers, :through => :subscriptions
  has_many :editions
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :customer
  belongs_to :publication

  def self.search(search)
    if search
        where(["publication_id LIKE ?","%#{search}%"])
      else
        all
      end
    end
end

app/models/upload.rb
class Upload < ApplicationRecord
belongs_to :user	
has_attached_file :image,
                storage: :s3,
              	s3_credentials: {access_key_id: ENV["AWS_KEY"], 
              	secret_access_key: ENV["AWS_SECRET"]},
              	bucket: "yghdassets"

validates_attachment_content_type :image, content_type: [/\Avideo\/.*\Z/, /\Aimage\/.*\Z/, /\Aapplication\/.*\Z/]
validates :submitter, presence: true
validates :email, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :registerable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/deductions_controller.rb
class DeductionsController < ApplicationController
  before_action :set_deduction, only: [:show, :edit, :update, :destroy]

  # GET /deductions
  # GET /deductions.json
  def index
    @deductions = Deduction.all
  end

  # GET /deductions/1
  # GET /deductions/1.json
  def show
  end

  # GET /deductions/new
  def new
    @deduction = Deduction.new
  end

  # GET /deductions/1/edit
  def edit
  end

  # POST /deductions
  # POST /deductions.json
  def create
    @deduction = Deduction.new(deduction_params)

    respond_to do |format|
      if @deduction.save
        format.html { redirect_to @deduction, notice: 'Deduction was successfully created.' }
        format.json { render :show, status: :created, location: @deduction }
      else
        format.html { render :new }
        format.json { render json: @deduction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /deductions/1
  # PATCH/PUT /deductions/1.json
  def update
    respond_to do |format|
      if @deduction.update(deduction_params)
        format.html { redirect_to @deduction, notice: 'Deduction was successfully updated.' }
        format.json { render :show, status: :ok, location: @deduction }
      else
        format.html { render :edit }
        format.json { render json: @deduction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /deductions/1
  # DELETE /deductions/1.json
  def destroy
    @deduction.destroy
    respond_to do |format|
      format.html { redirect_to deductions_url, notice: 'Deduction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_deduction
      @deduction = Deduction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def deduction_params
      params.require(:deduction).permit(:equipment_id, :link_to_return, :deduction_year, :cost, :elected_cost, :classification)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_helper.rb
module ChatHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/deductions_helper.rb
module DeductionsHelper
end

app/helpers/editions_helper.rb
module EditionsHelper
end

app/helpers/equipment_helper.rb
module EquipmentHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/deductions/_form.html.erb
<%= bootstrap_form_for(deduction) do |f| %>
  <% if deduction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(deduction.errors.count, "error") %> prohibited this deduction from being saved:</h2>

      <ul>
      <% deduction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.collection_select :equipment_id, Equipment.all, :id, :name %>
  </div>

  <div class="field">
    <%= f.text_field :link_to_return %>
  </div>

  <div class="field">
    <%= f.text_field :elected_cost %>
  </div>

  <div class="field">
    <%= f.text_field :classification %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/deductions/edit.html.erb
<h1>Editing Deduction</h1>

<%= render 'form', deduction: @deduction %>

<%= link_to 'Show', @deduction %> |
<%= link_to 'Back', deductions_path %>

app/views/deductions/index.html.erb
<p id="notice"><%= notice %></p>

<br>
<div class="jumbotron">
  <h1>Deductions</h1>
  <p>The Deductions Manager lists and manages deductions for physical assets.</p>


</div> 


<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Actions</h3>
  </div>
  <div class="panel-body">
    <a class="btn btn-primary btn-lg btn-block" href="/deductions/new" role="button">Add Deduction Item</a>
  </div>
</div>



<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Items</h3>
  </div>
  <div class="panel-body">
      <div class="table-responsive">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Show</th>
            <th>Edit</th>
            <th>Equipment</th>
            <th>Link to return</th>
            <th>Deduction year</th>
            <th>Cost</th>
            <th>Elected cost</th>
            <th>Classification</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @deductions.each do |deduction| %>
            <tr>
              <td>
              <button type="button" class="btn btn-default" aria-label="Left Align">
                <%= link_to '', deduction, :id => "button_id", :class => "glyphicon glyphicon-info-sign" %>
              </td>
              <td>
                <button type="button" class="btn btn-default" aria-label="Left Align">
                <%= link_to '', edit_deduction_path(deduction), :id => "button_id", :class => "glyphicon glyphicon-pencil" %>
              </td>
              <td><%= deduction.equipment.name %></td>
              <td><%= deduction.link_to_return %></td>
              <td><%= deduction.deduction_year %></td>
              <td><%= number_to_currency(deduction.equipment.amount) %></td>
              <td><%= number_to_currency(deduction.elected_cost) %></td>
              <td><%= deduction.classification %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    </div>
</div>
<br>

<%= link_to 'Home', '/' %>  |
<%= link_to 'Equipment', '/equipment' %>  |
<%= link_to 'New Item', new_deduction_path %>

app/views/deductions/new.html.erb
<h1>New Deduction</h1>

<%= render 'form', deduction: @deduction %>

<%= link_to 'Back', deductions_path %>

app/views/deductions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Equipment:</strong>
  <%= @deduction.equipment.name %>
</p>

<p>
  <strong>Link to return:</strong>
  <%= @deduction.link_to_return %>
</p>

<p>
  <strong>Deduction year:</strong>
  <%= @deduction.deduction_year %>
</p>

<p>
  <strong>Cost:</strong>
  <%= number_to_currency(@deduction.equipment.amount) %>
</p>

<p>
  <strong>Elected cost:</strong>
  <%= number_to_currency(@deduction.elected_cost) %>
</p>

<p>
  <strong>Classification:</strong>
  <%= @deduction.classification %>
</p>

<%= link_to 'Edit', edit_deduction_path(@deduction) %> |
<%= link_to 'Back', deductions_path %>