config/routes.rb
Rails.application.routes.draw do

  resources :orders
  resources :editions
  resources :subscriptions
  resources :publications
  get '/home/welcome', to: 'home#welcome'

  resources :uploads
  resources :deductions
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :customers
  resources :equipment
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

 # You can have the root of your site routed with "root"
  root to: 'home#index'
  get '/Sender', to: 'chat#Sender'
  get '/ReceiverOne', to: 'chat#ReceiverOne'
  get '/ReceiverTwo', to: 'chat#ReceiverTwo'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :orders
end

app/models/deduction.rb
class Deduction < ApplicationRecord
	belongs_to :equipment
end

app/models/edition.rb
class Edition < ApplicationRecord
  belongs_to :publication
end

app/models/equipment.rb
class Equipment < ApplicationRecord
	has_one :deduction
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  belongs_to :publication
  belongs_to :edition

  def self.search(search)
    if search
        where(["edition_id LIKE ?","%#{search}%"])
      else
        all
      end
    end
end

app/models/publication.rb
class Publication < ApplicationRecord
  has_many :subscriptions
  has_many :customers, :through => :subscriptions
  has_many :editions
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :customer
  belongs_to :publication

  def self.search(search)
    if search
        where(["publication_id LIKE ?","%#{search}%"])
      else
        all
      end
    end
end

app/models/upload.rb
class Upload < ApplicationRecord
belongs_to :user	
has_attached_file :image,
                storage: :s3,
              	s3_credentials: {access_key_id: ENV["AWS_KEY"], 
              	secret_access_key: ENV["AWS_SECRET"]},
              	bucket: "yghdassets"

validates_attachment_content_type :image, content_type: [/\Avideo\/.*\Z/, /\Aimage\/.*\Z/, /\Aapplication\/.*\Z/]
validates :submitter, presence: true
validates :email, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :registerable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :set_subscription, only: [:show, :edit, :update, :destroy]

  # GET /subscriptions
  # GET /subscriptions.json

  def index
    @subscriptions = Subscription.search(params[:search])
    @customers = Customer.all
    @publications = Publication.all
  end

  # GET /subscriptions/1
  # GET /subscriptions/1.json
  def show
  end

  # GET /subscriptions/new
  def new
    @subscription = Subscription.new
  end

  # GET /subscriptions/1/edit
  def edit
  end

  # POST /subscriptions
  # POST /subscriptions.json
  def create
    @subscription = Subscription.new(subscription_params)

    respond_to do |format|
      if @subscription.save
        format.html { redirect_to @subscription, notice: 'Subscription was successfully created.' }
        format.json { render :show, status: :created, location: @subscription }
      else
        format.html { render :new }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subscriptions/1
  # PATCH/PUT /subscriptions/1.json
  def update
    respond_to do |format|
      if @subscription.update(subscription_params)
        format.html { redirect_to @subscription, notice: 'Subscription was successfully updated.' }
        format.json { render :show, status: :ok, location: @subscription }
      else
        format.html { render :edit }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscriptions/1
  # DELETE /subscriptions/1.json
  def destroy
    @subscription.destroy
    respond_to do |format|
      format.html { redirect_to subscriptions_url, notice: 'Subscription was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscription
      @subscription = Subscription.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subscription_params
      params.require(:subscription).permit(:sign_up_date, :expiration_date, :notes, :publication_id, :customer_id, :name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_helper.rb
module ChatHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/deductions_helper.rb
module DeductionsHelper
end

app/helpers/editions_helper.rb
module EditionsHelper
end

app/helpers/equipment_helper.rb
module EquipmentHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/subscriptions/_form.html.erb
<%= form_for(subscription) do |f| %>
  <% if subscription.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(subscription.errors.count, "error") %> prohibited this subscription from being saved:</h2>

      <ul>
      <% subscription.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.collection_select( :customer_id, Customer.all, :id, :last_name) %>
  </div>

  <div class="field">
    <%= f.collection_select(:publication_id, Publication.all, :id, :name) %>
  </div>

  <div class="field">
    <%= f.label :sign_up_date %>
    <%= f.date_select :sign_up_date %>
  </div>

  <div class="field">
    <%= f.label :expiration_date %>
    <%= f.date_select :expiration_date %>
  </div>

  <div class="field">
    <%= f.label :notes %>
    <%= f.text_area :notes %>
  </div>




  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subscriptions/edit.html.erb
<h1>Editing Subscription</h1>

<%= render 'form', subscription: @subscription %>

<%= link_to 'Show', @subscription %> |
<%= link_to 'Back', subscriptions_path %>

app/views/subscriptions/index.html.erb
<p id="notice"><%= notice %></p>

<%= form_tag subscriptions_path, :method => 'get' do %>
  <%= collection_select(params[:search], :search, Publication.all, :id, :name, :prompt => true) %>
  <%= submit_tag "Search" %>
  <% end %>
  *narrow subscriptions by publication


<h1>Subscriptions</h1>

<table>
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Publication</th>
      <th>Sign up date</th>
      <th>Expiration date</th>
      <th>Notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subscriptions.each do |subscription| %>
      <tr>
        <td><%= subscription.customer.first_name %></td>
        <td><%= subscription.customer.last_name %></td>
        <td><%= subscription.publication.name %></td>
        <td><%= subscription.sign_up_date %></td>
        <td><%= subscription.expiration_date %></td>
        <td><%= subscription.notes %></td>
        <td><%= link_to 'Show', subscription %></td>
        <td><%= link_to 'Edit', edit_subscription_path(subscription) %></td>
        <td><%= link_to 'Destroy', subscription, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subscription', new_subscription_path %>

<br><br>

<%= link_to 'Home', '/' %>  |
<%= link_to 'List all subscriptions', subscriptions_path %>

app/views/subscriptions/new.html.erb
<h1>New Subscription</h1>

<%= render 'form', subscription: @subscription %>

<%= link_to 'Back', subscriptions_path %>

app/views/subscriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sign up date:</strong>
  <%= @subscription.sign_up_date %>
</p>

<p>
  <strong>Expiration date:</strong>
  <%= @subscription.expiration_date %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @subscription.notes %>
</p>

<%= link_to 'Edit', edit_subscription_path(@subscription) %> |
<%= link_to 'Back', subscriptions_path %>